services:
  postgres:
    image: postgres:17-alpine
    container_name: avito-kitchen-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-avito}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-avito}
      POSTGRES_DB: ${POSTGRES_DB:-avito_kitchen}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.18.3

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./migrations:/migrations:ro

    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER:-avito}:${POSTGRES_PASSWORD:-avito}@postgres:5432/${POSTGRES_DB:-avito_kitchen}?sslmode=disable",
        "up"
      ]

volumes:
  postgres_data: